import { z } from 'zod';

// All API input schemas. Limits are generous for real use but block abuse
// (multi-MB bodies, unbounded arrays) before anything reaches the DB or LLM.

export const journeyCreateSchema = z.object({
  name: z.string().trim().min(1).max(120),
  dream: z.string().trim().min(5).max(500),
  purpose: z.string().trim().max(1000).optional().default(''),
  timeframe: z.string().trim().max(120).optional().default(''),
  values: z.array(z.string().trim().min(1).max(40)).max(10).optional().default([]),
});

// UI entry-type keys only — mapping to type/moment_type happens server-side.
// clientRef: idempotency key generated by the form; a retry of the same
// submission reuses it so a client timeout can never create a duplicate.
export const entryCreateSchema = z.object({
  monumentId: z.string().uuid(),
  type: z.enum(['milestone', 'reflection', 'victory', 'failure', 'restart']),
  title: z.string().trim().max(200).optional().default(''),
  content: z.string().trim().min(1).max(5000),
  clientRef: z.string().uuid().optional(),
});

export const mentorMessageSchema = z.object({
  message: z.string().trim().min(1).max(4000),
});

// Parses a request body against a schema. Returns { data } or { error } with
// a human-readable message suitable for a 400 response.
export function parseBody(schema, body) {
  const result = schema.safeParse(body);
  if (result.success) return { data: result.data };
  const issue = result.error.issues[0];
  const path = issue.path.join('.');
  return { error: path ? `${path}: ${issue.message}` : issue.message };
}
